Cv-App.ApiService/Models/ErrorViewModel.cs
namespace Cv_App.ApiService.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Cv-App.ApiService/Controllers/CvModelsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Cv_App.Core.Models;
using Cv_App.Services.Interfaces;

namespace Cv_App.ApiService.Controllers
{
    public class CvModelsController : Controller
    {
        private readonly ICvDataService _cvDataService;

        public CvModelsController(ICvDataService cvDataService)
        {
            _cvDataService = cvDataService;
        }

        // GET: CvModels
        public async Task<IActionResult> Index()
        {
            return View(await _cvDataService.GetAllCvData());
        }

        // GET: CvModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cvModel = await _cvDataService.GetCvModelAsync(id.Value);
            if (cvModel == null)
            {
                return NotFound();
            }

            return View(cvModel);
        }

        // GET: CvModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CvModels/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("CvTitle,PersonalData,Educations,WorkExperiences,Properties")] CvModel cvModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _cvDataService.Create(cvModel);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException e)
            {
                ModelState.AddModelError("", e.Message);
            }
            return View(cvModel);
        }

        // GET: CvModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cvModel = await _cvDataService.GetCvModelAsync(id.Value);
            if (cvModel == null)
            {
                return NotFound();
            }
            return View(cvModel);
        }

        // POST: CvModels/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CvTitle,PersonalData,Educations,WorkExperiences,Properties")] CvModel cvModel)
        {
            if (id != cvModel.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    await _cvDataService.UpdateCv(cvModel);
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException e)
                {
                    ModelState.AddModelError("", e.Message);
                }
            }
            return View(cvModel);
        }

        // GET: CvModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cvModel = await _cvDataService.GetCvModelAsync(id.Value);
            if (cvModel == null)
            {
                return NotFound();
            }

            return View(cvModel);
        }

        // POST: CvModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cvModel = await _cvDataService.GetById(id);
            _cvDataService.Delete(cvModel);
            return RedirectToAction(nameof(Index));
        }
    }
}

Cv-App.ApiService/Controllers/HomeController.cs
using Cv_App.ApiService.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Cv_App.ApiService.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Cv-App.ApiService/Views/CvModels/Create.cshtml
@model Cv_App.Core.Models.CvModel

@{
    ViewData["Title"] = "Create";
}

<h1>Add new</h1>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/js/addCvProperties.js"></script>


<h4>CV</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CvTitle" class="control-label"></label>
                <input asp-for="CvTitle" class="form-control" />
                <span asp-validation-for="CvTitle" class="text-danger"></span>
            </div>
            <h4>Personal Data</h4>
            <div class="form-group">
                <label asp-for="PersonalData.Name" class="control-label"></label>
                <input asp-for="PersonalData.Name" class="form-control" />
                <span asp-validation-for="PersonalData.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PersonalData.LastName" class="control-label"></label>
                <input asp-for="PersonalData.LastName" class="form-control" />
                <span asp-validation-for="PersonalData.LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PersonalData.Email" class="control-label"></label>
                <input asp-for="PersonalData.Email" class="form-control" />
                <span asp-validation-for="PersonalData.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PersonalData.PhoneNumber" class="control-label"></label>
                <input asp-for="PersonalData.PhoneNumber" class="form-control" />
                <span asp-validation-for="PersonalData.PhoneNumber" class="text-danger"></span>
            </div>
            <h4>Education</h4>
            <div class="form-group" id="education"></div>
            <div class="form-group">
                <input type="button" id="addEducation" value="Add" />
            </div>
            <h4>Work Experience</h4>
            <div class="form-group" id="work"></div>
            <div class="form-group">
                <input type="button" id="addWorkExperience" value="Add" />
            </div>
            <h4>Other Information</h4>
            <div class="form-group" id="other"></div>
            <div class="form-group">
                <input type="button" id="addAdditionalInformation" value="Add" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Cv-App.ApiService/Views/CvModels/Delete.cshtml
@model Cv_App.Core.Models.CvModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this CV?</h3>
<div>
    <h4>CvModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CvTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CvTitle)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Cv-App.ApiService/Views/CvModels/Details.cshtml
@model Cv_App.Core.Models.CvModel

@{
    ViewData["Title"] = "Details";
}

<h3>Details</h3>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CvTitle)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CvTitle)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PersonalData.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PersonalData.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PersonalData.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PersonalData.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PersonalData.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PersonalData.PhoneNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PersonalData.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PersonalData.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Educations)
        </dt>
        <dd class="col-sm-10">
            <table class="table">
                <tr>
                    <th>Degree</th>
                    <th>Specialization</th>
                    <th>School</th>
                    <th>Duration</th>
                </tr>
                @foreach (var item in Model.Educations)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Degree)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Specialization)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.School)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StartDate) - @Html.DisplayFor(modelItem => item.EndDate)
                        </td>
                    </tr>
                }
            </table>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.WorkExperiences)
        </dt>
        <dd class="col-sm-10">
            <table class="table">
                <tr>
                    <th>Job title</th>
                    <th>Company</th>
                    <th>Duration</th>
                    <th>Job Description</th>
                </tr>
                @foreach (var item in Model.WorkExperiences)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.JobTitle)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Company)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StartDate) - @Html.DisplayFor(modelItem => item.EndDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.JobDescription)
                        </td>
                    </tr>
                }
            </table>
        </dd>
        @foreach (var item in Model.Properties)
        {
            <dt class="col-sm-2">
                @Html.DisplayFor(modelItem => item.Title)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(modelItem => item.Text)
            </dd>
        }
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Cv-App.ApiService/Views/CvModels/Edit.cshtml
@model Cv_App.Core.Models.CvModel

@{
    ViewData["Title"] = "Edit";
}
<div>
    <a asp-action="Details" asp-route-id="@Model.Id">Back to Details</a>
</div>
<h4>Edit</h4>
<script src="~/lib/jquery/dist/jquery.js"></script>

<script src="~/js/editCvProperties.js"></script>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CvTitle" class="control-label"></label>
                <input asp-for="CvTitle" class="form-control" />
                <span asp-validation-for="CvTitle" class="text-danger"></span>
            </div>
            <h5>Personal Data</h5>
            <div class="form-group">
                <label asp-for="PersonalData.Name" class="control-label"></label>
                <input asp-for="PersonalData.Name" class="form-control" />
                <span asp-validation-for="PersonalData.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PersonalData.LastName" class="control-label"></label>
                <input asp-for="PersonalData.LastName" class="form-control" />
                <span asp-validation-for="PersonalData.LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PersonalData.PhoneNumber" class="control-label"></label>
                <input asp-for="PersonalData.PhoneNumber" class="form-control" />
                <span asp-validation-for="PersonalData.PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PersonalData.Email" class="control-label"></label>
                <input asp-for="PersonalData.Email" class="form-control" />
                <span asp-validation-for="PersonalData.Email" class="text-danger"></span>
            </div>
            <h5>Education</h5>
            @for (int i = 0; i < Model.Educations.Count; i++)
            {
                    <div class="form-group">
                        <span class="additionalEducation">###########</span>
                        <div class="form-group">
                            <label class="control-label">Degree</label>
                            <input asp-for="Educations[i].Degree" class="form-control" />
                            <span asp-validation-for="Educations[i].Degree" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Specialization</label>
                            <input asp-for="Educations[i].Specialization" class="form-control" />
                            <span asp-validation-for="Educations[i].Specialization" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">School</label>
                            <input asp-for="Educations[i].School" class="form-control" />
                            <span asp-validation-for="Educations[i].School" class="text-danger"></span>
                        </div>
                        <h6>Duration</h6>
                        <div class="form-group">
                            <label class="control-label">Start Date</label>
                            <input asp-for="Educations[i].StartDate" class="form-control" />
                            <span asp-validation-for="Educations[i].StartDate" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">End Date </label>
                            <input asp-for="Educations[i].EndDate" class="form-control" />
                            <span asp-validation-for="Educations[i].EndDate" class="text-danger"></span>
                        </div>
                        <input type="button" class="removeElement" value="Remove" />
                    </div>
            }
            <div class="form-group" id="education"></div>
            <div class="form-group">
                <input type="button" class="addEducation" value="Add Education" />
            </div>
            <h5>Work Experience</h5>
            @for (int i = 0; i < Model.WorkExperiences.Count; i++)
            {
                <div class="form-group">
                    <span class="additionalWorkExperience">###########</span>
                    <div class="form-group">
                        <label class="control-label">Job Title</label>
                        <input asp-for="WorkExperiences[i].JobTitle" class="form-control" />
                        <span asp-validation-for="WorkExperiences[i].JobTitle" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Company</label>
                        <input asp-for="WorkExperiences[i].Company" class="form-control" />
                        <span asp-validation-for="WorkExperiences[i].Company" class="text-danger"></span>
                    </div>
                    <h6>Duration</h6>
                    <div class="form-group">
                        <label class="control-label">Start Date</label>
                        <input asp-for="WorkExperiences[i].StartDate" class="form-control" />
                        <span asp-validation-for="WorkExperiences[i].StartDate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">End Date</label>
                        <input asp-for="WorkExperiences[i].EndDate" class="form-control" />
                        <span asp-validation-for="WorkExperiences[i].EndDate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Job Description</label>
                        <input asp-for="WorkExperiences[i].JobDescription" class="form-control" style="width: 350px; height: 250px; text-align: justify"/>
                        <span asp-validation-for="WorkExperiences[i].JobDescription" class="text-danger"></span>
                    </div>
                    <input type="button" class="removeElement" value="Remove" />
                </div>
            }
            <div class="form-group" id="work"></div>
            <div class="form-group">
                <input type="button" class="addWorkExperience" value="Add Experience" />
            </div>
            <h5>Other Information</h5>
            @for (int i = 0; i < Model.Properties.Count; i++)
            {
                <div class="form-group">
                    <span class="additionalInfo">###########</span>
                    <div class="form-group">
                        <label class="control-label">Title</label>
                        <input asp-for="Properties[i].Title" class="form-control"/>
                        <span asp-validation-for="Properties[i].Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Text Field</label>
                        <input asp-for="Properties[i].Text" class="form-control" style="width: 350px; height: 250px; text-align: justify"/>
                        <span asp-validation-for="Properties[i].Text" class="text-danger"></span>
                    </div>
                    <input type="button" class="removeElement" value="Remove" />
                </div>
            }
            <div class="form-group" id="other"></div>
            <div class="form-group">
                <input type="button" class="addAdditionalInformation" value="Add Information" />
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save Changes" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Details" asp-route-id="@Model.Id">Back to Details</a>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Cv-App.ApiService/Views/CvModels/Index.cshtml
@model IEnumerable<Cv_App.Core.Models.CvModel>

@{
    ViewData["Title"] = "Home";
}

<h1>CV list</h1>

<p>
    <a asp-action="Create">Create New CV</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CvTitle)
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CvTitle)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Cv-App.ApiService/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <div style="display:inline-block">Start working with your CV here - <a asp-area="" asp-controller="CvModels" asp-action="Index"><strong>Browse CV</strong></a></div>
</div>

Cv-App.ApiService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cv App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CvModels" asp-action="Index">Browse CV</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>